// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUm1fesfEY6RKOewYy32rxLxcSbPXz0Jc',
    appId: '1:756396144541:web:2fcb302017ee0c055fa174',
    messagingSenderId: '756396144541',
    projectId: 'fir-authentication-a0ea3',
    authDomain: 'fir-authentication-a0ea3.firebaseapp.com',
    storageBucket: 'fir-authentication-a0ea3.firebasestorage.app',
    measurementId: 'G-RSKX5C2CQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtRspY08YOh7PAzWMiz2J0zBiG-YDX600',
    appId: '1:756396144541:android:cd1c22c1065bd4765fa174',
    messagingSenderId: '756396144541',
    projectId: 'fir-authentication-a0ea3',
    storageBucket: 'fir-authentication-a0ea3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA85GPoUQ6F-KhFipwiv7aTfKxIzRMrqOg',
    appId: '1:756396144541:ios:fd236006db4002ea5fa174',
    messagingSenderId: '756396144541',
    projectId: 'fir-authentication-a0ea3',
    storageBucket: 'fir-authentication-a0ea3.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthenticationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA85GPoUQ6F-KhFipwiv7aTfKxIzRMrqOg',
    appId: '1:756396144541:ios:fd236006db4002ea5fa174',
    messagingSenderId: '756396144541',
    projectId: 'fir-authentication-a0ea3',
    storageBucket: 'fir-authentication-a0ea3.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthenticationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUm1fesfEY6RKOewYy32rxLxcSbPXz0Jc',
    appId: '1:756396144541:web:250f152258d1947d5fa174',
    messagingSenderId: '756396144541',
    projectId: 'fir-authentication-a0ea3',
    authDomain: 'fir-authentication-a0ea3.firebaseapp.com',
    storageBucket: 'fir-authentication-a0ea3.firebasestorage.app',
    measurementId: 'G-PD66J55RS7',
  );
}
